Repository cse110-sp23-group27/Fortune-Telling-Group-27, pull requests merged in 2023-06, with the labels that each got.

#83 Home page
  assets/scripts/index.js
  assets/styles/home-page.css
  index.html
Labels: bug, Priority, homepage-related

#85 Home page
  assets/scripts/Animator.js
  assets/scripts/TarotCard.js
  assets/scripts/index.js
Labels: bug

#123 Fog opacity
  assets/styles/tarot-page.css
  specs/documentation/generated/assets_scripts_Animator.js.html
  specs/documentation/generated/assets_scripts_TarotCard.js.html
  specs/documentation/generated/assets_scripts_index.js.html
  specs/documentation/generated/assets_scripts_service-worker.js.html
  specs/documentation/generated/global.html
  specs/documentation/generated/global.html#Animator
  specs/documentation/generated/global.html#TarotCard
  specs/documentation/generated/index.html
  specs/documentation/generated/jest_tests_e2e_tests_E2EHelperFunctions.js.html
  specs/documentation/generated/jest_tests_e2e_tests_burgerBarE2E.test.js.html
  specs/documentation/generated/jest_tests_e2e_tests_homepageE2E.test.js.html
  specs/documentation/generated/jest_tests_e2e_tests_tarotCardE2E.test.js.html
Labels: tarot card animation

#163 Added font changes to branch for pull request
  assets/styles/home-page.css
  assets/styles/tarot-page.css
  fonts/CinzelDecorative-Black.ttf
  fonts/CinzelDecorative-Bold.ttf
  fonts/CinzelDecorative-Regular.ttf
Labels: enhancement, text feature, Non-urgent, text responses, homepage-related

#170 Second burger bar branch
  assets/scripts/index.js
  assets/styles/home-page.css
  index.html
  specs/documentation/generated/assets_scripts_Animator.js.html
  specs/documentation/generated/assets_scripts_TarotCard.js.html
  specs/documentation/generated/assets_scripts_index.js.html
  specs/documentation/generated/assets_scripts_service-worker.js.html
  specs/documentation/generated/global.html
  specs/documentation/generated/global.html#Animator
  specs/documentation/generated/global.html#TarotCard
  specs/documentation/generated/index.html
  specs/documentation/generated/jest_tests_e2e_tests_E2EHelperFunctions.js.html
  specs/documentation/generated/jest_tests_e2e_tests_burgerBarE2E.test.js.html
  specs/documentation/generated/jest_tests_e2e_tests_homepageE2E.test.js.html
Labels: Extra feature, homepage-related, local storage

#173 Second burger bar branch
  assets/images/bookClosed.png
  assets/images/openBook.png
  assets/styles/home-page.css
  index.html
Labels: enhancement, Extra feature, homepage-related

#175 Fixed image link pathways
  assets/scripts/service-worker.js
  assets/styles/home-page.css
  index.html
  specs/documentation/generated/assets_scripts_service-worker.js.html
  specs/documentation/generated/global.html
Labels: bug

#176 Text display opacity
  assets/scripts/index.js
  assets/styles/tarot-page.css
  specs/documentation/generated/assets_scripts_index.js.html
  specs/documentation/generated/global.html
Labels: text responses

#178 Book change access branch
  assets/scripts/consts.js
  assets/scripts/index.js
  assets/styles/home-page.css
  index.html
Labels: Priority, local storage

#167 Adding sound effects for the buttons
  assets/audio/button-click.mp3
  assets/audio/card-select.mp3
  assets/audio/menu-slider.mp3
  assets/audio/shuffling-card.mp3
  assets/scripts/index.js
  index.html
  specs/documentation/generated/assets_scripts_index.js.html
  specs/documentation/generated/global.html
Labels: Extra feature
